#include <stdio.h>
#include <stdlib.h>

int main()
{
    /* INT FPRINTF(FILE *FP, CONST CHAR *FMT, PROMJENLJIVE) */
    /* INT FSCANF(FILE *FP, CONST CHAR*FMT, PROMJENLJIVE) */
    /* INT GETC(FILE *FP) */
    /* CHAR *FGETS(CHAR *S, INT N, FILE *FP)

    CHAR *S - GDJE CE SE SKLADISTITI POKUPLJEN STRING
    INT N KOLIKO CE MAKSIMALNO UZIMATI(GLEDA I NULLTI KARAKTER ZA KRAJ STRINGA)
     */
    return 0;
}
